"""
C++ node mapping registration.

This module owns Python-side mapping from derived node ids to C++ builder
factories exposed from ``hgraph._hgraph``.
"""

from __future__ import annotations

from hgraph._wiring import merge_cpp_node_mappings

__all__ = ("register_cpp_node_mappings",)


def register_cpp_node_mappings(_hgraph_module) -> None:
    merge_cpp_node_mappings({
        "hgraph": {
            "const_default": _hgraph_module.op_const_default,
            "nothing_impl": _hgraph_module.op_nothing_impl,
            "null_sink_impl": _hgraph_module.op_null_sink_impl,
            "add_float_to_int": _hgraph_module.op_add_float_to_int,
            "add_int_to_int": _hgraph_module.op_add_int_to_int,
            "add_float_to_float": _hgraph_module.op_add_float_to_float,
            "add_int_to_float": _hgraph_module.op_add_int_to_float,
            "sub_int_from_int": _hgraph_module.op_sub_int_from_int,
            "sub_float_from_float": _hgraph_module.op_sub_float_from_float,
            "sub_int_from_float": _hgraph_module.op_sub_int_from_float,
            "sub_float_from_int": _hgraph_module.op_sub_float_from_int,
            "mul_float_and_int": _hgraph_module.op_mul_float_and_int,
            "mul_int_and_int": _hgraph_module.op_mul_int_and_int,
            "mul_float_and_float": _hgraph_module.op_mul_float_and_float,
            "mul_int_and_float": _hgraph_module.op_mul_int_and_float,
            "lshift_ints": _hgraph_module.op_lshift_ints,
            "rshift_ints": _hgraph_module.op_rshift_ints,
            "bit_and_ints": _hgraph_module.op_bit_and_ints,
            "bit_or_ints": _hgraph_module.op_bit_or_ints,
            "bit_xor_ints": _hgraph_module.op_bit_xor_ints,
            "eq_float_int": _hgraph_module.op_eq_float_int,
            "eq_int_int": _hgraph_module.op_eq_int_int,
            "eq_int_float": _hgraph_module.op_eq_int_float,
            "eq_float_float": _hgraph_module.op_eq_float_float,
            "ne_int_int": _hgraph_module.op_ne_int_int,
            "ne_int_float": _hgraph_module.op_ne_int_float,
            "ne_float_int": _hgraph_module.op_ne_float_int,
            "ne_float_float": _hgraph_module.op_ne_float_float,
            "lt_int_int": _hgraph_module.op_lt_int_int,
            "lt_int_float": _hgraph_module.op_lt_int_float,
            "lt_float_int": _hgraph_module.op_lt_float_int,
            "lt_float_float": _hgraph_module.op_lt_float_float,
            "le_int_int": _hgraph_module.op_le_int_int,
            "le_int_float": _hgraph_module.op_le_int_float,
            "le_float_int": _hgraph_module.op_le_float_int,
            "le_float_float": _hgraph_module.op_le_float_float,
            "gt_int_int": _hgraph_module.op_gt_int_int,
            "gt_int_float": _hgraph_module.op_gt_int_float,
            "gt_float_int": _hgraph_module.op_gt_float_int,
            "gt_float_float": _hgraph_module.op_gt_float_float,
            "ge_int_int": _hgraph_module.op_ge_int_int,
            "ge_int_float": _hgraph_module.op_ge_int_float,
            "ge_float_int": _hgraph_module.op_ge_float_int,
            "ge_float_float": _hgraph_module.op_ge_float_float,
            "neg_int": _hgraph_module.op_neg_int,
            "neg_float": _hgraph_module.op_neg_float,
            "pos_int": _hgraph_module.op_pos_int,
            "pos_float": _hgraph_module.op_pos_float,
            "invert_int": _hgraph_module.op_invert_int,
            "abs_int": _hgraph_module.op_abs_int,
            "abs_float": _hgraph_module.op_abs_float,
            "ln_impl": _hgraph_module.op_ln_impl,
            "eq_enum": _hgraph_module.op_eq_enum,
            "lt_enum": _hgraph_module.op_lt_enum,
            "le_enum": _hgraph_module.op_le_enum,
            "gt_enum": _hgraph_module.op_gt_enum,
            "ge_enum": _hgraph_module.op_ge_enum,
            "getattr_enum_name": _hgraph_module.op_getattr_enum_name,
            "div_numbers": _hgraph_module.op_div_numbers,
            "floordiv_numbers": _hgraph_module.op_floordiv_numbers,
            "floordiv_ints": _hgraph_module.op_floordiv_ints,
            "mod_numbers": _hgraph_module.op_mod_numbers,
            "mod_ints": _hgraph_module.op_mod_ints,
            "pow_int_float": _hgraph_module.op_pow_int_float,
            "pow_float_int": _hgraph_module.op_pow_float_int,
            "divmod_numbers": _hgraph_module.op_divmod_numbers,
            "divmod_ints": _hgraph_module.op_divmod_ints,
            "add_scalars": _hgraph_module.op_add_scalars,
            "sub_scalars": _hgraph_module.op_sub_scalars,
            "mul_scalars": _hgraph_module.op_mul_scalars,
            "pow_scalars": _hgraph_module.op_pow_scalars,
            "lshift_scalars": _hgraph_module.op_lshift_scalars,
            "rshift_scalars": _hgraph_module.op_rshift_scalars,
            "bit_and_scalars": _hgraph_module.op_bit_and_scalars,
            "bit_or_scalars": _hgraph_module.op_bit_or_scalars,
            "bit_xor_scalars": _hgraph_module.op_bit_xor_scalars,
            "eq_scalars": _hgraph_module.op_eq_scalars,
            "ne_scalars": _hgraph_module.op_ne_scalars,
            "lt_scalars": _hgraph_module.op_lt_scalars,
            "le_scalars": _hgraph_module.op_le_scalars,
            "gt_scalars": _hgraph_module.op_gt_scalars,
            "ge_scalars": _hgraph_module.op_ge_scalars,
            "neg_scalar": _hgraph_module.op_neg_scalar,
            "pos_scalar": _hgraph_module.op_pos_scalar,
            "invert_scalar": _hgraph_module.op_invert_scalar,
            "abs_scalar": _hgraph_module.op_abs_scalar,
            "len_scalar": _hgraph_module.op_len_scalar,
            "cmp_scalars": _hgraph_module.op_cmp_scalars,
            "not_scalar": _hgraph_module.op_not_scalar,
            "and_scalars": _hgraph_module.op_and_scalars,
            "or_scalars": _hgraph_module.op_or_scalars,
            "contains_scalar": _hgraph_module.op_contains_scalar,
            "add_str": _hgraph_module.op_add_str,
            "mul_strs": _hgraph_module.op_mul_strs,
            "contains_str": _hgraph_module.op_contains_str,
            "substr_default": _hgraph_module.op_substr_default,
            "and_booleans": _hgraph_module.op_and_booleans,
            "or_booleans": _hgraph_module.op_or_booleans,
            "not_boolean": _hgraph_module.op_not_boolean,
        }
    })
