import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath("."))

project = "hgraph"
author = "Howard Henson"
copyright = f"{datetime.now().year}, {author}"
release = "0.8"

extensions = [
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinxcontrib.bibtex",
    "sphinxcontrib.mermaid",
    "myst_parser",
]

# Autodoc is deliberately absent. The operator surface resolves lazily through
# ``hgraph.__getattr__`` over the native operator registry, so the checked-in
# reference inventory is generated by ``tools/api_inventory.py`` from a built
# wheel. This keeps ordinary documentation builds compiler-free while still
# checking the documented public surface against the runtime.

templates_path = ["_templates"]
exclude_patterns = ["_build", "build", "Thumbs.db", ".DS_Store"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
}
intersphinx_disabled_domains = ["std"]

# Only run examples explicitly marked with `testcode`/`doctest` directives.
# Without this, `sphinx-build -b doctest` also harvests bare `>>>` blocks,
# including third-party doctests embedded in re-exported numpy docstrings.
doctest_test_doctest_blocks = ""

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
html_theme_options = {
    "collapse_navigation": True,
    "sticky_navigation": True,
    "navigation_depth": 3,
    "includehidden": True,
    "titles_only": False,
}

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "tasklist",
]
myst_fence_as_directive = ["mermaid"]
# The specification pages use `##`-level headings under a `#` title; without
# this MyST refuses to build a section hierarchy deeper than the toctree depth.
myst_heading_anchors = 3

bibtex_bibfiles = ["references.bib"]
bibtex_default_style = "alpha"
bibtex_reference_style = "author_year"

latex_engine = "xelatex"
epub_show_urls = "footnote"
