cmake_minimum_required(VERSION 3.25)

foreach(_required IN ITEMS
        HGL_SNAPSHOT_MODE
        HGL_SNAPSHOT_DIRECTORY
        HGL_SNAPSHOT_WORK_DIRECTORY
        HGL_GENERATED_NATIVE_HEADER
        HGL_GENERATED_NATIVE_SOURCE
        HGL_GENERATED_STANDARD_HEADER
        HGL_GENERATED_STANDARD_SOURCE)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "HglGeneratedCppSnapshot.cmake requires ${_required}")
    endif()
endforeach()

if(NOT HGL_SNAPSHOT_MODE STREQUAL "CHECK" AND NOT HGL_SNAPSHOT_MODE STREQUAL "UPDATE")
    message(FATAL_ERROR "HGL_SNAPSHOT_MODE must be CHECK or UPDATE")
endif()

set(_hgl_snapshot_drift)

macro(_hgl_snapshot generated relative)
    if(NOT EXISTS "${generated}")
        message(FATAL_ERROR "generated C++ input does not exist: ${generated}")
    endif()

    file(READ "${generated}" _hgl_generated_content)
    string(REGEX MATCH
        "^// Generated by hgl [^\r\n]+ from [^\r\n;]+; do not edit\\."
        _hgl_generated_banner
        "${_hgl_generated_content}")
    if(NOT _hgl_generated_banner)
        message(FATAL_ERROR "generated C++ input has no recognized hgl banner: ${generated}")
    endif()
    string(REGEX REPLACE
        "^// Generated by hgl [^\r\n]+ from ([^\r\n;]+); do not edit\\."
        "// Generated by hgl <version> from \\1; do not edit."
        _hgl_normalized_content
        "${_hgl_generated_content}")

    set(_hgl_snapshot_path "${HGL_SNAPSHOT_DIRECTORY}/${relative}")
    if(HGL_SNAPSHOT_MODE STREQUAL "UPDATE")
        get_filename_component(_hgl_snapshot_parent "${_hgl_snapshot_path}" DIRECTORY)
        file(MAKE_DIRECTORY "${_hgl_snapshot_parent}")
        set(_hgl_existing_content)
        if(EXISTS "${_hgl_snapshot_path}")
            file(READ "${_hgl_snapshot_path}" _hgl_existing_content)
        endif()
        if(NOT _hgl_existing_content STREQUAL _hgl_normalized_content)
            file(WRITE "${_hgl_snapshot_path}" "${_hgl_normalized_content}")
            message(STATUS "updated ${_hgl_snapshot_path}")
        endif()
    elseif(NOT EXISTS "${_hgl_snapshot_path}")
        list(APPEND _hgl_snapshot_drift "${relative} (missing)")
    else()
        file(READ "${_hgl_snapshot_path}" _hgl_expected_content)
        if(NOT _hgl_expected_content STREQUAL _hgl_normalized_content)
            set(_hgl_actual_path "${HGL_SNAPSHOT_WORK_DIRECTORY}/${relative}")
            get_filename_component(_hgl_actual_parent "${_hgl_actual_path}" DIRECTORY)
            file(MAKE_DIRECTORY "${_hgl_actual_parent}")
            file(WRITE "${_hgl_actual_path}" "${_hgl_normalized_content}")
            list(APPEND _hgl_snapshot_drift "${relative} (actual: ${_hgl_actual_path})")
        endif()
    endif()
endmacro()

_hgl_snapshot("${HGL_GENERATED_NATIVE_HEADER}" native.h)
_hgl_snapshot("${HGL_GENERATED_NATIVE_SOURCE}" native.cpp)
_hgl_snapshot("${HGL_GENERATED_STANDARD_HEADER}" standard.h)
_hgl_snapshot("${HGL_GENERATED_STANDARD_SOURCE}" standard.cpp)

if(_hgl_snapshot_drift)
    list(JOIN _hgl_snapshot_drift "\n  " _hgl_snapshot_drift_text)
    message(FATAL_ERROR
        "generated C++ snapshots differ:\n  ${_hgl_snapshot_drift_text}\n"
        "Run the hgl_refresh_generated_cpp_snapshots target and review the resulting diff.")
endif()
