import pytest
from hgraph._feature_switch import is_feature_enabled


def test_cpp_node_builder_factories_are_exposed():
    import hgraph._hgraph as _hgraph

    assert hasattr(_hgraph, "op_nothing_impl")
    assert hasattr(_hgraph, "op_null_sink_impl")
    assert hasattr(_hgraph, "op_const_default")
    for factory_name in (
        "op_add_float_to_int",
        "op_add_int_to_int",
        "op_add_float_to_float",
        "op_add_int_to_float",
        "op_sub_int_from_int",
        "op_sub_float_from_float",
        "op_sub_int_from_float",
        "op_sub_float_from_int",
        "op_mul_float_and_int",
        "op_mul_int_and_int",
        "op_mul_float_and_float",
        "op_mul_int_and_float",
        "op_lshift_ints",
        "op_rshift_ints",
        "op_bit_and_ints",
        "op_bit_or_ints",
        "op_bit_xor_ints",
        "op_div_numbers",
        "op_floordiv_numbers",
        "op_floordiv_ints",
        "op_mod_numbers",
        "op_mod_ints",
        "op_divmod_numbers",
        "op_divmod_ints",
        "op_pow_int_float",
        "op_pow_float_int",
        "op_add_scalars",
        "op_sub_scalars",
        "op_mul_scalars",
        "op_pow_scalars",
        "op_lshift_scalars",
        "op_rshift_scalars",
        "op_bit_and_scalars",
        "op_bit_or_scalars",
        "op_bit_xor_scalars",
        "op_eq_scalars",
        "op_ne_scalars",
        "op_lt_scalars",
        "op_le_scalars",
        "op_gt_scalars",
        "op_ge_scalars",
        "op_neg_scalar",
        "op_pos_scalar",
        "op_invert_scalar",
        "op_abs_scalar",
        "op_len_scalar",
        "op_cmp_scalars",
        "op_not_scalar",
        "op_and_scalars",
        "op_or_scalars",
        "op_contains_scalar",
        "op_getattr_cs",
        "op_getattr_type_name",
        "op_getitem_tuple_fixed",
        "op_getitem_tuple",
        "op_getitem_frozendict",
        "op_get_item_series",
        "op_get_item_series_ts",
        "op_getattr_json_str",
        "op_getattr_json_bool",
        "op_getattr_json_int",
        "op_getattr_json_float",
        "op_getattr_json_obj",
        "op_getitem_json_str",
        "op_getitem_json_int",
        "op_eq_int_int",
        "op_eq_float_int",
        "op_eq_int_float",
        "op_eq_float_float",
        "op_ne_int_int",
        "op_ne_int_float",
        "op_ne_float_int",
        "op_ne_float_float",
        "op_lt_int_int",
        "op_lt_int_float",
        "op_lt_float_int",
        "op_lt_float_float",
        "op_le_int_int",
        "op_le_int_float",
        "op_le_float_int",
        "op_le_float_float",
        "op_gt_int_int",
        "op_gt_int_float",
        "op_gt_float_int",
        "op_gt_float_float",
        "op_ge_int_int",
        "op_ge_int_float",
        "op_ge_float_int",
        "op_ge_float_float",
        "op_neg_int",
        "op_neg_float",
        "op_pos_int",
        "op_pos_float",
        "op_invert_int",
        "op_abs_int",
        "op_abs_float",
        "op_add_str",
        "op_mul_strs",
        "op_contains_str",
        "op_substr_default",
        "op_str_default",
        "op_str_bytes",
        "op_match_default",
        "op_replace_default",
        "op__split_default",
        "op_join_str_tuple",
        "op_format_",
        "op_type_cs_schema",
        "op_type_cs_typevar",
        "op_type_scalar",
        "op_cast_impl",
        "op_downcast_impl",
        "op_downcast_ref_impl",
        "op_modified_impl",
        "op_last_modified_time_impl",
        "op_last_modified_date_impl",
        "op_evaluation_time_in_range_date_time",
        "op_and_booleans",
        "op_or_booleans",
        "op_not_boolean",
        "op_eq_enum",
        "op_lt_enum",
        "op_le_enum",
        "op_gt_enum",
        "op_ge_enum",
        "op_getattr_enum_name",
        "op_ln_impl",
    ):
        assert hasattr(_hgraph, factory_name)


def test_cpp_node_builder_factory_requires_signature_and_scalars():
    import hgraph._hgraph as _hgraph

    with pytest.raises(TypeError, match="signature"):
        _hgraph.op_nothing_impl()


@pytest.mark.skipif(not is_feature_enabled("use_cpp"), reason="C++ runtime only")
def test_cpp_operator_mappings_are_registered():
    import hgraph._hgraph as _hgraph
    from hgraph._wiring._cpp_node_registry import lookup_cpp_node_builder

    assert lookup_cpp_node_builder("hgraph::const_default") is _hgraph.op_const_default
    assert lookup_cpp_node_builder("hgraph::nothing_impl") is _hgraph.op_nothing_impl
    assert lookup_cpp_node_builder("hgraph::null_sink_impl") is _hgraph.op_null_sink_impl
    expected_mappings = {
        "hgraph::add_float_to_int": _hgraph.op_add_float_to_int,
        "hgraph::add_int_to_int": _hgraph.op_add_int_to_int,
        "hgraph::add_float_to_float": _hgraph.op_add_float_to_float,
        "hgraph::add_int_to_float": _hgraph.op_add_int_to_float,
        "hgraph::sub_int_from_int": _hgraph.op_sub_int_from_int,
        "hgraph::sub_float_from_float": _hgraph.op_sub_float_from_float,
        "hgraph::sub_int_from_float": _hgraph.op_sub_int_from_float,
        "hgraph::sub_float_from_int": _hgraph.op_sub_float_from_int,
        "hgraph::mul_float_and_int": _hgraph.op_mul_float_and_int,
        "hgraph::mul_int_and_int": _hgraph.op_mul_int_and_int,
        "hgraph::mul_float_and_float": _hgraph.op_mul_float_and_float,
        "hgraph::mul_int_and_float": _hgraph.op_mul_int_and_float,
        "hgraph::lshift_ints": _hgraph.op_lshift_ints,
        "hgraph::rshift_ints": _hgraph.op_rshift_ints,
        "hgraph::bit_and_ints": _hgraph.op_bit_and_ints,
        "hgraph::bit_or_ints": _hgraph.op_bit_or_ints,
        "hgraph::bit_xor_ints": _hgraph.op_bit_xor_ints,
        "hgraph::div_numbers": _hgraph.op_div_numbers,
        "hgraph::floordiv_numbers": _hgraph.op_floordiv_numbers,
        "hgraph::floordiv_ints": _hgraph.op_floordiv_ints,
        "hgraph::mod_numbers": _hgraph.op_mod_numbers,
        "hgraph::mod_ints": _hgraph.op_mod_ints,
        "hgraph::divmod_numbers": _hgraph.op_divmod_numbers,
        "hgraph::divmod_ints": _hgraph.op_divmod_ints,
        "hgraph::pow_int_float": _hgraph.op_pow_int_float,
        "hgraph::pow_float_int": _hgraph.op_pow_float_int,
        "hgraph::add_scalars": _hgraph.op_add_scalars,
        "hgraph::sub_scalars": _hgraph.op_sub_scalars,
        "hgraph::mul_scalars": _hgraph.op_mul_scalars,
        "hgraph::pow_scalars": _hgraph.op_pow_scalars,
        "hgraph::lshift_scalars": _hgraph.op_lshift_scalars,
        "hgraph::rshift_scalars": _hgraph.op_rshift_scalars,
        "hgraph::bit_and_scalars": _hgraph.op_bit_and_scalars,
        "hgraph::bit_or_scalars": _hgraph.op_bit_or_scalars,
        "hgraph::bit_xor_scalars": _hgraph.op_bit_xor_scalars,
        "hgraph::eq_scalars": _hgraph.op_eq_scalars,
        "hgraph::ne_scalars": _hgraph.op_ne_scalars,
        "hgraph::lt_scalars": _hgraph.op_lt_scalars,
        "hgraph::le_scalars": _hgraph.op_le_scalars,
        "hgraph::gt_scalars": _hgraph.op_gt_scalars,
        "hgraph::ge_scalars": _hgraph.op_ge_scalars,
        "hgraph::neg_scalar": _hgraph.op_neg_scalar,
        "hgraph::pos_scalar": _hgraph.op_pos_scalar,
        "hgraph::invert_scalar": _hgraph.op_invert_scalar,
        "hgraph::abs_scalar": _hgraph.op_abs_scalar,
        "hgraph::len_scalar": _hgraph.op_len_scalar,
        "hgraph::cmp_scalars": _hgraph.op_cmp_scalars,
        "hgraph::not_scalar": _hgraph.op_not_scalar,
        "hgraph::and_scalars": _hgraph.op_and_scalars,
        "hgraph::or_scalars": _hgraph.op_or_scalars,
        "hgraph::contains_scalar": _hgraph.op_contains_scalar,
        "hgraph::getattr_cs": _hgraph.op_getattr_cs,
        "hgraph::getattr_type_name": _hgraph.op_getattr_type_name,
        "hgraph::getitem_tuple_fixed": _hgraph.op_getitem_tuple_fixed,
        "hgraph::getitem_tuple": _hgraph.op_getitem_tuple,
        "hgraph::getitem_frozendict": _hgraph.op_getitem_frozendict,
        "hgraph::get_item_series": _hgraph.op_get_item_series,
        "hgraph::get_item_series_ts": _hgraph.op_get_item_series_ts,
        "hgraph::getattr_json_str": _hgraph.op_getattr_json_str,
        "hgraph::getattr_json_bool": _hgraph.op_getattr_json_bool,
        "hgraph::getattr_json_int": _hgraph.op_getattr_json_int,
        "hgraph::getattr_json_float": _hgraph.op_getattr_json_float,
        "hgraph::getattr_json_obj": _hgraph.op_getattr_json_obj,
        "hgraph::getitem_json_str": _hgraph.op_getitem_json_str,
        "hgraph::getitem_json_int": _hgraph.op_getitem_json_int,
        "hgraph::eq_int_int": _hgraph.op_eq_int_int,
        "hgraph::eq_float_int": _hgraph.op_eq_float_int,
        "hgraph::eq_int_float": _hgraph.op_eq_int_float,
        "hgraph::eq_float_float": _hgraph.op_eq_float_float,
        "hgraph::ne_int_int": _hgraph.op_ne_int_int,
        "hgraph::ne_int_float": _hgraph.op_ne_int_float,
        "hgraph::ne_float_int": _hgraph.op_ne_float_int,
        "hgraph::ne_float_float": _hgraph.op_ne_float_float,
        "hgraph::lt_int_int": _hgraph.op_lt_int_int,
        "hgraph::lt_int_float": _hgraph.op_lt_int_float,
        "hgraph::lt_float_int": _hgraph.op_lt_float_int,
        "hgraph::lt_float_float": _hgraph.op_lt_float_float,
        "hgraph::le_int_int": _hgraph.op_le_int_int,
        "hgraph::le_int_float": _hgraph.op_le_int_float,
        "hgraph::le_float_int": _hgraph.op_le_float_int,
        "hgraph::le_float_float": _hgraph.op_le_float_float,
        "hgraph::gt_int_int": _hgraph.op_gt_int_int,
        "hgraph::gt_int_float": _hgraph.op_gt_int_float,
        "hgraph::gt_float_int": _hgraph.op_gt_float_int,
        "hgraph::gt_float_float": _hgraph.op_gt_float_float,
        "hgraph::ge_int_int": _hgraph.op_ge_int_int,
        "hgraph::ge_int_float": _hgraph.op_ge_int_float,
        "hgraph::ge_float_int": _hgraph.op_ge_float_int,
        "hgraph::ge_float_float": _hgraph.op_ge_float_float,
        "hgraph::neg_int": _hgraph.op_neg_int,
        "hgraph::neg_float": _hgraph.op_neg_float,
        "hgraph::pos_int": _hgraph.op_pos_int,
        "hgraph::pos_float": _hgraph.op_pos_float,
        "hgraph::invert_int": _hgraph.op_invert_int,
        "hgraph::abs_int": _hgraph.op_abs_int,
        "hgraph::abs_float": _hgraph.op_abs_float,
        "hgraph::add_str": _hgraph.op_add_str,
        "hgraph::mul_strs": _hgraph.op_mul_strs,
        "hgraph::contains_str": _hgraph.op_contains_str,
        "hgraph::substr_default": _hgraph.op_substr_default,
        "hgraph::str_default": _hgraph.op_str_default,
        "hgraph::str_bytes": _hgraph.op_str_bytes,
        "hgraph::match_default": _hgraph.op_match_default,
        "hgraph::replace_default": _hgraph.op_replace_default,
        "hgraph::_split_default": _hgraph.op__split_default,
        "hgraph::join_str_tuple": _hgraph.op_join_str_tuple,
        "hgraph::format_": _hgraph.op_format_,
        "hgraph::type_cs_schema": _hgraph.op_type_cs_schema,
        "hgraph::type_cs_typevar": _hgraph.op_type_cs_typevar,
        "hgraph::type_scalar": _hgraph.op_type_scalar,
        "hgraph::cast_impl": _hgraph.op_cast_impl,
        "hgraph::downcast_impl": _hgraph.op_downcast_impl,
        "hgraph::downcast_ref_impl": _hgraph.op_downcast_ref_impl,
        "hgraph::modified_impl": _hgraph.op_modified_impl,
        "hgraph::last_modified_time_impl": _hgraph.op_last_modified_time_impl,
        "hgraph::last_modified_date_impl": _hgraph.op_last_modified_date_impl,
        "hgraph::evaluation_time_in_range_date_time": _hgraph.op_evaluation_time_in_range_date_time,
        "hgraph::and_booleans": _hgraph.op_and_booleans,
        "hgraph::or_booleans": _hgraph.op_or_booleans,
        "hgraph::not_boolean": _hgraph.op_not_boolean,
        "hgraph::eq_enum": _hgraph.op_eq_enum,
        "hgraph::lt_enum": _hgraph.op_lt_enum,
        "hgraph::le_enum": _hgraph.op_le_enum,
        "hgraph::gt_enum": _hgraph.op_gt_enum,
        "hgraph::ge_enum": _hgraph.op_ge_enum,
        "hgraph::getattr_enum_name": _hgraph.op_getattr_enum_name,
        "hgraph::ln_impl": _hgraph.op_ln_impl,
    }
    for cpp_node_id, expected_factory in expected_mappings.items():
        assert lookup_cpp_node_builder(cpp_node_id) is expected_factory
