"""Generated semantic documentation for native operator proxies.

Source summaries live on the public C++ operator declarations; exact
accepted signatures come from the runtime registry."""

OPERATOR_DOCS = {
    'abs_': '``abs_`` — the ``abs`` operator (``abs(ts) -> OUT``).',
    'add_': '``add_`` — the ``+`` operator. Operands and result may all differ (``lhs + rhs -> OUT``).',
    'all_': '``all_`` — graph ``all``: ``True`` when every boolean input is ``True`` (variadic).',
    'and_': '``and_`` — the ``and`` operator (truthy combination), yielding ``TS<Bool>``.',
    'any_': '``any_`` — graph ``any``: ``True`` when any boolean input is ``True`` (variadic).',
    'apply': '``apply`` — invoke a ticking runtime callable and publish its result.',
    'as_array': 'Convert a fixed tick window into a shaped array, optionally padding with ``zero``.',
    'assert_': '``assert_`` — assert ``condition`` holds, raising ``error_msg`` otherwise (a sink).',
    'at_zone': '``at_zone`` — represent an instant in the supplied time zone.',
    'batch': '``batch`` — like ``gate`` but releases queued ticks in batches with ``delay`` between them.',
    'bit_and': '``bit_and`` — the ``&`` operator (``lhs & rhs -> OUT``).',
    'bit_or': '``bit_or`` — the ``|`` operator (``lhs | rhs -> OUT``).',
    'bit_xor': '``bit_xor`` — the ``^`` operator (``lhs ^ rhs -> OUT``).',
    'call': '``call`` — invoke a ticking runtime callable for side effects.',
    'clip': '``clip`` — clip ``ts`` into the ``[min, max]`` range.',
    'cmp_': '``cmp_`` — three-way comparison; returns ``LT`` / ``EQ`` / ``GT`` in one step.',
    'collapse_keys': '``collapse_keys`` — flatten nested TSD keys into tuple keys.',
    'collect': '``collect`` — accumulate ``ts`` into a collection time-series (output type via ``OUT``).',
    'combine': '``combine`` — build a typed composite time-series. Overloads cover temporal values, collections, structured values, mappings, keyed dictionaries, sets, and dynamic JSON.',
    'compare': '``compare`` — the backtesting comparison sink (COMPARE mode): records per-tick equality of ``lhs`` vs ``rhs`` through the registered frame store (P6) under ``fq_recordable_id.__compare__``.',
    'concat': '``concat(ts1, ts2)`` — append rows from two frames with the same schema.',
    'const': "``const_`` — a source that emits a configured ``value`` once at the start cycle, or ``delay`` after it. The output type is the registered ``TS`` of the value's type, or an explicit output schema at the wiring site (``wire<const_, TSS<Int>>(w, set_value)``). Two arities: ``const(value)`` (tick at start) and ``const(value, delay)`` (tick at ``start_time + delay``).",
    'contains_': '``contains_`` — the ``in`` operator: ``item in ts`` -> ``TS<Bool>``.',
    'convert': '``convert`` — convert the incoming time-series to the requested output type.',
    'convert_zone': '``convert_zone`` — view a zoned datetime in another zone without changing its instant.',
    'corrcoef': 'Native correlation coefficients, with an optional second array.',
    'count': '``count`` — a running count of the ticks of ``ts`` (optional ``reset`` signal).',
    'cumsum': 'Native cumulative sum. The optional scalar axis is supplied as a second argument.',
    'day': '``day`` — the day-of-month attribute of a date or datetime.',
    'day_of_month': '``day_of_month`` — the day-of-month of a ``TS<Date>``.',
    'days': "hgraph's timedelta ATTRIBUTES (port.days / .seconds / .microseconds) and ``total_seconds()`` — issue #82. Python's normalization: ``days`` floors toward -inf; ``seconds`` / ``microseconds`` are the non-negative remainders.",
    'debug_print': '``debug_print`` — print ``label: value`` on each tick of ``ts`` (a diagnostic sink). (Python also takes ``print_delta`` / ``sample`` — not yet modelled.)',
    'dedup': '``dedup`` — drop consecutive duplicate values.',
    'default': '``default_`` — pass ``ts`` through, substituting ``default_value`` while ``ts`` is invalid.',
    'dereference': '``dereference`` — materialize ``REF[TSB[...]]`` or ``REF[TSL[...]]`` as the same container shape whose children reference the corresponding children of the referenced container.',
    'diff': '``diff`` — the difference between the current and previous value of ``ts``.',
    'difference': '``difference_`` — set difference (``lhs`` minus the rest).',
    'dispatch_': '``dispatch_`` — select a child graph from the active concrete Bundle leaf types of one or more ``TS[Bundle]`` arguments. The small native selector feeds the existing ``switch_`` runtime; branch arguments are checked-downcast to their declared case types inside the child graph.',
    'div_': '``div_`` — the ``/`` (true division) operator (``lhs / rhs -> OUT``). Implementations may take an optional ``Scalar<"divide_by_zero", DivideByZero>`` wiring-time policy.',
    'divmod_': '``divmod_`` — the ``divmod`` operator. Result is a 2-element list ``(quotient, remainder)``.',
    'downcast_': '``downcast_`` — downcast a ``TS`` value to a (checked) derived type.',
    'downcast_ref': '``downcast_ref`` — downcast a ``REF`` to a derived type (fast, unchecked).',
    'drop': '``drop`` — drop the first ``count`` ticks of ``ts``, then forward the rest.',
    'emit': "``emit`` — stream a collection's elements out as individual ticks.",
    'eq_': '``eq_`` — the ``==`` operator.',
    'evaluation_time_in_range': '``evaluation_time_in_range`` — where the evaluation time sits relative to [start, end]: LT / EQ / GT, self-scheduling at the boundaries (datetime / date / daily-recurring time overloads).',
    'ewma': '``ewma`` — an exponential moving average of ``ts`` with smoothing ``alpha``.',
    'explode': '``explode`` — split a date into a fixed list of year, month, and day.',
    'filter_': '``filter_`` — suppress ticks of ``ts`` while ``condition`` is ``False``.',
    'filter_by': 'Keep TSD entries where ``expr(value, **kwargs)`` is true.\n\n``map_`` computes the per-key matches; the grouped native override applies\nthose matches to the dictionary.',
    'filter_cs': 'Filter a frame by the set fields of one compound scalar value.',
    'filter_frame': 'Filter a frame by the currently valid fields of a structural TSB.',
    'flip': '``flip`` — swap keys and values of a dictionary.',
    'flip_keys': '``flip_keys`` — invert the outer/inner keys of a nested ``TSD[K, TSD[K1, V]]``.',
    'floordiv_': '``floordiv_`` — the ``//`` (floor division) operator (``lhs // rhs -> OUT``).',
    'format_': '``format_`` — format the supplied time-series values into a string using ``fmt`` (variadic args).',
    'freeze': '``freeze`` — forward ``ts`` until ``predicate`` first holds, then passivate ``ts`` (stop forwarding).',
    'from_data_frame': 'Data-frame convenience operators (design record: *Record/replay, tables and const_fn*, step 6): the same layout/codec machinery as ``to_table`` with a plain ``date`` column and no ``as_of``.\n\n``from_data_frame[OUT](df, dt_col="date", key_col="key", value_col="value", offset=0)`` replays a frame VALUE by its date column (a pull source; TSD forms take the key from ``key_col``). ``to_data_frame(ts, ...)`` snapshots the time-series per tick into a one-tick frame whose columns come from the requested output ``Frame[Schema]``. ``group_by(ts, by)`` partitions a Frame-valued TS into ``TSD[key, TS[Frame]]`` by column name(s).',
    'from_data_frame_batches': 'Replay successively supplied frame batches without concatenating the source. Each batch must arrive no later than its first retained row.',
    'from_json': '``from_json`` — parse JSON text as the explicitly selected output schema.',
    'from_table': '``from_table`` — apply bitemporal tuple rows as deltas of the selected output schema.',
    'from_table_const': '``from_table_const`` — the const-evaluable read of a recorded FRAME value (the replay_const seam): extract the (last) row of a frame VALUE as the output type.',
    'gate': '``gate`` — queue ticks while ``condition`` is ``False``, releasing them once it is ``True``.',
    'ge_': '``ge_`` — the ``>=`` operator.',
    'get_item': 'Apply a wiring-time integer or integer-tuple index to a shaped array.',
    'getattr_': '``getattr_`` — the ``.`` (attribute access) operator: ``ts.attr``. ``attr`` is a wiring-time string; an optional ``default_value`` may be supplied by an implementation.',
    'getitem_': '``getitem_`` — the ``[]`` operator: ``ts[key]``.',
    'group_by': '``group_by`` — partition a frame-valued time-series by one or more columns.',
    'gt_': '``gt_`` — the ``>`` operator.',
    'hour': "hgraph's datetime / time ATTRIBUTES (port.hour / .minute / .second / .microsecond) plus the datetime methods (``weekday()`` / ``isoweekday()`` / ``timestamp()``) — issue #82. The datetime overloads register under the existing ``year`` / ``month`` / ``day`` / ``weekday`` / ``isoweekday`` markers.",
    'if_': '``if_`` — route ``ts`` to a ``true`` / ``false`` bundle output by ``condition``.',
    'if_cmp': '``if_cmp`` — select ``lt`` / ``eq`` / ``gt`` according to a ``CmpResult``.',
    'if_then_else': '``if_then_else`` — select ``true_value`` or ``false_value`` per ``condition``.',
    'if_true': '``if_true`` — tick ``True`` when ``condition`` ticks ``True`` (optional ``tick_once_only``).',
    'index_of': '``index_of`` — the index of ``item`` within ``ts`` -> ``TS<Int>``.',
    'intersection': '``intersection_`` — set intersection of the inputs.',
    'invert_': '``invert_`` — the unary ``~`` (bitwise invert) operator (``~ts -> OUT``).',
    'is_empty': '``is_empty`` — whether the time-series value is considered empty -> ``TS<Bool>``.',
    'isoformat': '``isoformat`` — format a date, datetime, or time as an ISO 8601 string.',
    'isoweekday': '``isoweekday`` — the ISO day of the week using Monday as one.',
    'join': 'Arrow-native equi-join. The namespace avoids colliding with the string join marker; both remain overloads in the public family.\n\n``join`` — join several string time-series with ``separator`` (variadic).',
    'json_as_bool': '``json_as_bool`` — coerce a dynamic JSON leaf to a boolean.',
    'json_as_float': '``json_as_float`` — coerce a dynamic JSON leaf to a floating-point value.',
    'json_as_int': '``json_as_int`` — coerce a dynamic JSON leaf to an integer.',
    'json_as_str': '``json_as_str`` — coerce a dynamic JSON leaf to a string.',
    'json_decode': '``json_decode`` — parse JSON text into the dynamic JSON-tree value type.',
    'json_encode': '``json_encode`` — encode a dynamic JSON-tree value as JSON text.',
    'keys_': '``keys_`` — the keys of a dictionary (as a ``TSS`` / set).',
    'lag': '``lag`` — delay delivery of ``ts`` by ``period`` ticks (or a time-delta).',
    'last_modified_date': '``last_modified_date`` — the date component of the last-modified time.',
    'last_modified_time': '``last_modified_time`` — the evaluation time ``ts`` was last modified.',
    'last_modified_wall_clock_time': '``last_modified_wall_clock_time`` — the wall-clock time ``ts`` was last modified.',
    'le_': '``le_`` — the ``<=`` operator.',
    'len_': '``len_`` — the ``len`` operator -> ``TS<Int>``.',
    'ln': '``ln`` — the natural logarithm of a ``TS<Float>`` value.',
    'log_': '``log_`` — format and log the supplied values at ``level`` (a sink, with positional and named time-series arguments).',
    'lshift_': '``lshift_`` — the ``<<`` operator (``lhs << rhs -> OUT``).',
    'lt_': '``lt_`` — the ``<`` operator.',
    'make_tsd': 'Build/update one keyed TSD entry from a key and arbitrary time-series value.\n\nThree-input C++ wiring form with an explicit remove signal.',
    'map_': '``map_`` — apply a child graph independently to each keyed or list element.\n\nOutputless keyed map. Resolves through the same ``map_`` registry name.',
    'match_': '``match_`` — match a regex ``pattern`` against ``s``; result is a bundle (``is_match`` / ``groups``).',
    'max_': '``max_`` — binary element-wise maximum. Collection / variadic forms are separate overloads.',
    'mean': '``mean`` — running / element-wise mean.',
    'merge': '``merge`` — forward the first input that ticks in the current cycle.',
    'mesh_': "``mesh_(func, *args, **kwargs)`` — like ``map_`` over a ``TSD``, but the per-key instances may read each other's outputs (``mesh_(func)[k]``), create instances on demand, and evaluate in dependency-rank order within a cycle. The instantiation call surface mirrors ``map_``; cross-instance access uses ``mesh_ref<OUT>(w, key)`` inside the mesh body. See the developer guide *Mesh*. TSD argument classification, including generic whole-time-series inputs and ``pass_through`` / ``no_key`` tags, follows ``map_`` exactly; mesh does not implement map's TSL kernels.",
    'microsecond': '``microsecond`` — the microsecond component of a datetime or time.',
    'microseconds': '``microseconds`` — the non-negative microsecond remainder of a timedelta.',
    'min_': '``min_`` — binary element-wise minimum. Collection / variadic forms are separate overloads.',
    'minute': '``minute`` — the minute component of a datetime or time.',
    'mod_': '``mod_`` — the ``%`` operator (``lhs % rhs -> OUT``).',
    'modified': '``modified`` — ``True`` in the cycle ``ts`` is modified (a live, ticking property).',
    'month': "hgraph's date ATTRIBUTES (port.month / .day / .weekday / .isoweekday).",
    'month_of_year': '``month_of_year`` — the month-of-year of a ``TS<Date>``.',
    'mul_': '``mul_`` — the ``*`` operator (``lhs * rhs -> OUT``). (Python takes an optional ``__strict__`` flag.)',
    'ne_': '``ne_`` — the ``!=`` operator.',
    'neg_': '``neg_`` — the unary ``-`` operator (``-ts -> OUT``).',
    'not_': '``not_`` — the unary ``not`` operator, yielding ``TS<Bool>``.',
    'nothing': '``nothing`` — a source that never ticks, of the requested output type.',
    'np_std': 'Population/sample standard deviation over a numeric shaped array.',
    'null_sink': '``null_sink`` — consume ``ts`` and do nothing (a terminal sink).',
    'or_': '``or_`` — the ``or`` operator, yielding ``TS<Bool>``.',
    'partition': '``partition`` — split a ``TSD[K, V]`` into ``TSD[K1, TSD[K, V]]`` using a mapping.',
    'pct_change': 'Fractional change from the immediately preceding value.',
    'pos_': '``pos_`` — the unary ``+`` operator (``+ts -> OUT``).',
    'pow_': '``pow_`` — the ``**`` operator (``lhs ** rhs -> OUT``).',
    'print_': '``print_`` — format and write the supplied values to std-out (a sink, variadic args).',
    'quantile': 'Native scalar quantile over an array or time-series window.',
    'race': '``race`` — forward the first valid input, falling through when it invalidates.',
    'range_adjacent': '``range_adjacent`` — test whether endpoints coincide with exactly one of them closed.',
    'range_contains': '``range_contains`` — test whether a temporal range contains a value or another range.',
    'range_difference': '``range_difference`` — subtract the right-hand range from the left-hand range.',
    'range_extent': "``range_extent`` — return the duration between an instant range's boundaries.",
    'range_hull': '``range_hull`` — return the smallest range spanning both inputs.',
    'range_intersection': '``range_intersection`` — return the common portion of two temporal ranges.',
    'range_merge': '``range_merge`` — merge two mergeable ranges into one range.',
    'range_mergeable': '``range_mergeable`` — test whether two ranges overlap or are adjacent.',
    'range_overlaps': '``range_overlaps`` — test whether two temporal ranges share any included instant.',
    'range_shift': '``range_shift`` — move both range boundaries by a duration or calendar period.',
    'range_touches': '``range_touches`` — test whether finite endpoint values coincide, regardless of openness.',
    'range_union': '``range_union`` — return the normalized union of two temporal ranges.',
    'record': '``record`` — record ``ts`` under ``key`` (a sink).',
    'reduce': '``reduce`` — reduce a time-series **collection** into a single time-series with the (associative) combiner ``func``. Mirrors Python ``reduce(func, ts[, zero], is_associative=true)``. For associative reduction, ``zero`` has deliberately narrow semantics:\n\n- no live values: publish ``zero`` when supplied, otherwise remain invalid; - one live value: return that value directly when ``zero`` is omitted, or evaluate ``func(value, zero)`` when it is supplied; - two or more live values: reduce only those values; ``zero`` is not an operand.\n\n- ``ts`` — any multiplexed collection (``TSL`` / ``TSD``; ``TSS`` once the Python reference grows one). Each collection kind is its own registered overload of this name, selected by pattern rank — implemented today: fixed/dynamic ``TSL`` and ``TSD``. - ``zero`` — **optional**, modelled as arity overloads (like ``const``): when supplied as a scalar, the value is wired as ``const(zero)`` at the element schema. Unset ``TSL`` slots are not live values. - ``is_associative=false`` — select an ordered left fold. A fixed TSL folds statically; a contiguous ``TSD[int, E]`` uses the live ``zero`` input as its initial accumulator and permits an accumulator type that differs from ``E``.',
    'reduce_tsd_of_bundles_with_race': '``reduce_tsd_of_bundles_with_race`` — bundle-flavoured keyed race reduction.',
    'reduce_tsd_with_race': '``reduce_tsd_with_race(tsd=TSD<K, REF<OUT>>) -> REF<OUT>`` — keyed race (hgraph parity; ``reduce_tsd_of_bundles_with_race`` is the same erased implementation registered under the bundle-flavoured name).',
    'rekey': '``rekey`` — re-key the input dictionary using a mapping time-series.',
    'replace': '``replace`` — replace ``pattern`` with ``repl`` in ``s``.',
    'replay': '``replay`` — replay a recorded series for ``key`` as the requested output type (a source).',
    'replay_const': '``replay_const`` — replay the const value(s) at/under ``key`` valid up to the start time.',
    'replay_data_frame': 'Replay a canonical bitemporal table frame through the native table protocol, selecting the latest as-of revision per partition.',
    'request_id': '``request_id`` — a process-unique identifier allocated at node start.',
    'resample': '``resample`` — re-tick ``ts`` at ``period``, even when the input does not tick.',
    'resolve_civil': '``resolve_civil`` — resolve a local civil time using explicit daylight-saving policies.',
    'rolling_average': "``rolling_average`` — the trailing average of ``ts`` by tick count or duration (hgraph's window helper: ``(sum(ts) - sum(lag(ts, period)))`` over the covered tick count).",
    'rolling_window_arrays': "Materialize a window's values and evaluation timestamps as shaped arrays.",
    'round_': "``round_`` — round a float to ``n_digits`` decimal places (python's correctly-rounded decimal semantics).",
    'route_by_index': '``route_by_index`` — forward ``ts`` to the ``index``-th of a list of outputs.',
    'rshift_': '``rshift_`` — the ``>>`` operator (``lhs >> rhs -> OUT``).',
    'sample': '``sample`` — snap ``ts`` on each tick of ``signal``.',
    'schedule': '``schedule`` — a source ticking ``True`` every ``delay``.',
    'second': '``second`` — the second component of a datetime or time.',
    'seconds': '``seconds`` — the non-negative whole-second remainder of a timedelta.',
    'setattr_': '``setattr_`` — sets ``ts.attr`` to ``value`` and returns the updated bundle.',
    'sign': '``sign`` — Python-compatible numeric sign: ``-1`` for negative values, ``+1`` otherwise.',
    'slice_': '``slice_`` — ``drop`` + ``take`` + ``step`` combined over ``[start, stop)`` by ``step_size``.',
    'sorted_': '``sorted_(ts, by, descending=false)`` — order a typed frame by one column.',
    'split': '``split`` — split ``s`` over ``separator`` into the requested output shape.\n\nFixed TSL output size is an output type decision, not an input-derived fact. Callers must supply the output schema explicitly, for example:\n\n``wire<stdlib::split, TSL<TS<Str>, 2>>(w, s, Str{","})``.',
    'std': '``std_`` — running / element-wise standard deviation. Window overloads accept ``ddof`` to use an ``N - ddof`` divisor.',
    'step': '``step`` — forward every ``step_size``-th tick of ``ts``.',
    'stop_engine': '``stop_engine`` — request an orderly engine stop after this cycle.',
    'str_': '``str_`` — convert the incoming time-series to its ``TS<Str>`` representation.',
    'sub_': '``sub_`` — the ``-`` operator (``lhs - rhs -> OUT``).',
    'substr': '``substr`` — extract a substring of ``s`` between ``start`` and ``end``.',
    'sum_': '``sum_`` — running / element-wise sum.',
    'switch_': "``switch_`` — route through **one** child graph at a time, selected by ``key``. Mirrors Python ``switch_(key, cases, *ts)``:\n\n- on a key change the active branch is stopped and destroyed, the branch for the new key (else the default, else a runtime error) is built, bound and started, and the output **re-points** — sampling the new branch at the switch time (the sampled-runtime contract; a deliberate divergence from Python's ``value = None`` reset); - a branch may take the key as its first argument when that parameter is named ``key``; - the time-series arguments are variadic (``*ts``): branches bind them positionally, optionally preceded by the key.\n\nThe outputless form of ``switch_``. Both markers resolve through the same operator registry name; this marker makes the output contract explicit to C++'s static ``wire<>`` return type.",
    'symmetric_difference': '``symmetric_difference_`` — set symmetric difference of the inputs.',
    'take': '``take`` — forward only the first ``count`` ticks of ``ts``.',
    'temporal_bucket': '``temporal_bucket`` — return the fixed-width instant range containing a value.',
    'temporal_ceil': '``temporal_ceil`` — round a temporal value up to a quantum boundary.',
    'temporal_floor': '``temporal_floor`` — round a temporal value down to a quantum boundary.',
    'temporal_round': '``temporal_round`` — round a temporal value to its nearest quantum boundary.',
    'throttle': '``throttle`` — limit the tick rate of ``ts`` to ``period``.',
    'timestamp': "``timestamp`` — FRACTIONAL seconds since the Unix epoch (Python's ``datetime.timestamp()`` returns a float). hgraph datetimes are UTC by convention, so this is the UTC epoch count (upstream's naive ``datetime.timestamp()`` is local-tz dependent; recorded deviation).",
    'to_civil': '``to_civil`` — extract the local civil date and time from a zoned datetime.',
    'to_data_frame': '``to_data_frame`` — snapshot each time-series tick as a typed frame.',
    'to_instant': '``to_instant`` — extract the absolute instant from a zoned datetime.',
    'to_json': "JSON serialization operators (design record: *Record/replay, tables and const_fn*, step 1). The wire format is the Python one — see ``types/value/json_codec.h``.\n\n``to_json(ts, delta=false)`` serialises the time-series VALUE per tick; with ``delta=true`` it serialises the canonical per-tick delta value (``capture_delta``) instead — the canonical delta *is* the recorded delta wire form.\n\n``from_json`` parses into the resolved output type and applies the parsed value as the tick's delta: ``wire<from_json, TS<MySchema>>(w, ts)``.",
    'to_table': "Table serialization operators (design record: *Record/replay, tables and const_fn*, P4 + step 6). ``to_table`` is the Python-parity TUPLE-ROW protocol: each tick converts to bitemporal row values ``[date, as_of, {removed, *keys}(per TSD level), *value columns]`` — ``TS<tuple[...]>`` for single-row types, ``TS<tuple[tuple[...], ...]>`` for partitioned (TSD) or multi-row (``Frame``-valued) types; unset cells are tuple field validity (Python ``None``). The output schema is computed from the resolved input at wiring. ``mode`` is a ``ToTableMode`` enum time-series (Tick/Sample/Snap) defaulting to Tick.\n\n``from_table`` reverses it, applying each row as the tick's delta at the resolved output (supplied at the wiring site: ``wire<from_table, TS<MySchema>>(w, ts)``); removed flags map to TSD key removals. The record/replay backends bypass both and drive the Arrow serializer ops directly (``types/value/table_codec.h``).",
    'to_window': '``to_window`` — convert ``ts`` into a ``TSW`` time-series window of ``period`` ticks, valid once ``min_window_period`` ticks arrived. An optional ``reset`` SIGNAL overload clears retained ticks before admitting a source tick from the same evaluation cycle.',
    'total_seconds': '``total_seconds`` — convert a timedelta to fractional seconds.',
    'try_except': '``try_except`` — run one child graph and expose captured node errors alongside its output.',
    'type_': '``type_`` — the (python) type of the time-series value.',
    'uncollapse_keys': '``uncollapse_keys`` — the inverse of ``collapse_keys`` (optional ``remove_empty`` flag).',
    'ungroup': 'Concatenate the valid values of a keyed frame collection.\n\nUngroup while materializing a scalar or tuple key into columns.',
    'union': '``union_`` — set union of the inputs.',
    'unpartition': '``unpartition`` — merge a nested ``TSD[K1, TSD[K, V]]`` back into ``TSD[K, V]``.',
    'until_true': '``until_true`` — emit ``False`` until ``predicate`` first holds, then ``True`` (and passivate ``ts``).',
    'valid': '``valid`` — ``True`` while ``ts`` is valid, ``False`` otherwise.',
    'values_': '``values_`` — the values of a dictionary.',
    'var': '``var_`` — running / element-wise variance.',
    'weekday': '``weekday`` — the day of the week using Monday as zero.',
    'window': '``window`` — buffer the last ``period`` values; result is a bundle (buffer + timestamps).',
    'with_columns': 'Replace/add structural columns and project to the output row schema.',
    'year': '``year`` — the year of a ``TS<Date>``.',
    'zero': '``zero_`` — the zero source for a requested output type and operation (mirrors Python ``zero(tp, op)``: the value depends on both — e.g. ``add_`` -> 0 but ``mul_`` -> 1). ``op`` is the wired function (``fn<add_>()``).',
}
