#include "wiring/backend.h"
#include <bytes-values.h>
#include <catch2/catch_test_macros.hpp>
#include <hgl/execution_error.h>
#include <hgl/ordinary_values.h>
#include <hgraph/lib/testing/check_output.h>
#include <hgraph/lib/testing/eval_node.h>

using namespace hgraph;
using namespace hgraph::testing;
namespace bytes_values = checks::bytes_values;

TEST_CASE("generated bytes construct complete ordinary lists and count octets", "[codegen][bytes]") {
    hgl::wiring::ensure_session();
    bytes_values::register_operators();
    const hgl::ordinary::PreparedValuePlan list{scalar_descriptor<hgl::ordinary::List<Int>>::value_meta()};
    const Value                            zero{Int{0}}, last{Int{255}}, bad{Int{256}};
    auto                                   payload = list.empty_list();
    list.push(payload.view(), zero.view());
    list.push(payload.view(), last.view());
    auto invalid = list.empty_list();
    list.push(invalid.view(), bad.view());
    const Bytes expected{std::string{"\0\xff", 2}};
    CHECK_OUTPUT(
        (eval_node<bytes_values::operators::construct, TS<hgl::ordinary::List<Int>>>(values<Value>(payload, none, payload))),
        values<Bytes>(expected, none, expected));
    CHECK_OUTPUT(eval_node<bytes_values::count>(values<Bytes>(Bytes{}, expected, none, expected)), values<Int>(0, 2, none, 2));
    CHECK(bytes_values::hgl_values::from_octets_hgl_value(payload.view()) == expected);
    CHECK(bytes_values::hgl_values::byte_count_hgl_value(expected) == 2);
    const auto expect_range = [](auto call) {
        try {
            call();
            FAIL("out-of-range octet unexpectedly constructed bytes");
        } catch (const std::exception &error) { CHECK(hgl::execution_error_code(error) == "value.byte_range"); }
    };
    expect_range(
        [&] { (void)eval_node<bytes_values::operators::construct, TS<hgl::ordinary::List<Int>>>(values<Value>(invalid)); });
    expect_range([&] { (void)eval_node<bytes_values::constant_failure>(values<Int>(1)); });
}
