// Adapted from Cameron Desrochers' moodycamel::ConcurrentQueue FreeList.
// Source:
// https://github.com/cameron314/concurrentqueue/blob/master/concurrentqueue.h
//
// Copyright (c) 2013-2020, Cameron Desrochers.
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and all
// derivative works of the Software, unless such copies or derivative works are
// solely in the form of machine-executable object code generated by a source
// language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
// ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
#ifndef HGRAPH_TYPES_VALUE_IMPL_LOCK_FREE_FREELIST_H
#define HGRAPH_TYPES_VALUE_IMPL_LOCK_FREE_FREELIST_H

#include <atomic>
#include <cassert>
#include <cstdint>

namespace hgraph::value_impl {
/**
 * ABA-safe intrusive free list for nodes that remain allocated for the
 * list's lifetime. ``free_list_refs`` protects an observed head while its
 * next pointer is read; it is intentionally separate from a slot's value
 * reference count.
 */
template <typename Node> class LockFreeFreeList {
public:
  LockFreeFreeList() noexcept = default;
  LockFreeFreeList(const LockFreeFreeList &) = delete;
  LockFreeFreeList &operator=(const LockFreeFreeList &) = delete;

  void add(Node *node) noexcept {
    // The should-be-on-list bit is known to be clear here.
    if (node->free_list_refs.fetch_add(SHOULD_BE_ON_LIST,
                                       std::memory_order_acq_rel) == 0) {
      add_knowing_refcount_is_zero(node);
    }
  }

  [[nodiscard]] Node *try_get() noexcept {
    Node *head = head_.load(std::memory_order_acquire);
    while (head != nullptr) {
      Node *previous = head;
      auto refs = head->free_list_refs.load(std::memory_order_relaxed);
      if ((refs & REFS_MASK) == 0 ||
          !head->free_list_refs.compare_exchange_strong(
              refs, refs + 1, std::memory_order_acquire,
              std::memory_order_relaxed)) {
        head = head_.load(std::memory_order_acquire);
        continue;
      }

      Node *next = head->free_list_next.load(std::memory_order_relaxed);
      if (head_.compare_exchange_strong(head, next, std::memory_order_acquire,
                                        std::memory_order_relaxed)) {
        assert((previous->free_list_refs.load(std::memory_order_relaxed) &
                SHOULD_BE_ON_LIST) == 0);
        previous->free_list_refs.fetch_sub(2, std::memory_order_release);
        return previous;
      }

      refs = previous->free_list_refs.fetch_sub(1, std::memory_order_acq_rel);
      if (refs == SHOULD_BE_ON_LIST + 1) {
        add_knowing_refcount_is_zero(previous);
      }
    }
    return nullptr;
  }

private:
  void add_knowing_refcount_is_zero(Node *node) noexcept {
    Node *head = head_.load(std::memory_order_relaxed);
    while (true) {
      node->free_list_next.store(head, std::memory_order_relaxed);
      node->free_list_refs.store(1, std::memory_order_release);
      if (!head_.compare_exchange_strong(head, node, std::memory_order_release,
                                         std::memory_order_relaxed)) {
        if (node->free_list_refs.fetch_add(SHOULD_BE_ON_LIST - 1,
                                           std::memory_order_acq_rel) == 1) {
          continue;
        }
      }
      return;
    }
  }

  static constexpr std::uint32_t REFS_MASK = 0x7fffffffU;
  static constexpr std::uint32_t SHOULD_BE_ON_LIST = 0x80000000U;

  std::atomic<Node *> head_{nullptr};
};
} // namespace hgraph::value_impl

#endif // HGRAPH_TYPES_VALUE_IMPL_LOCK_FREE_FREELIST_H
