#!/usr/bin/env python3
"""Generate the checked Python API inventory and lazy-operator type stub.

Run this with an installed hgraph wheel (or a built extension on
``PYTHONPATH``). The root package, native operator registry, and public module
``__all__`` declarations are deliberately separate inputs: none of them is a
complete API description by itself.
"""

from __future__ import annotations

import argparse
import ast
import importlib
import keyword
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RST = ROOT / "docs/source/reference/python_api_inventory.rst"
DEFAULT_STUB = ROOT / "python/hgraph/_operator_typing.pyi"

PUBLIC_MODULES = (
    "hgraph.temporal",
    "hgraph.nodes",
    "hgraph.test",
    "hgraph.debug",
    "hgraph.stream",
    "hgraph.reflection",
    "hgraph.numpy_",
    "hgraph.arrow",
    "hgraph.notebook",
    "hgraph.adaptors.data_catalogue",
    "hgraph.adaptors.data_frame",
    "hgraph.adaptors.dataclass",
    "hgraph.adaptors.delta",
    "hgraph.adaptors.executor",
    "hgraph.adaptors.json",
    "hgraph.adaptors.perspective",
    "hgraph.adaptors.run_graph_on_thread",
    "hgraph.adaptors.sql",
    "hgraph.adaptors.tornado",
)


def _literal_all(module_name: str) -> tuple[str, ...]:
    """Read a literal ``__all__`` without importing an optional adaptor."""
    relative = Path(*module_name.split("."))
    if relative.parts[0] != "hgraph":
        return ()
    module_path = ROOT / "python" / relative
    source = module_path / "__init__.py"
    if not source.exists():
        source = module_path.with_suffix(".py")
    if not source.exists():
        return ()
    tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
    for statement in tree.body:
        if not isinstance(statement, (ast.Assign, ast.AnnAssign)):
            continue
        targets = statement.targets if isinstance(statement, ast.Assign) else [statement.target]
        if not any(isinstance(target, ast.Name) and target.id == "__all__" for target in targets):
            continue
        try:
            value = ast.literal_eval(statement.value)
        except (TypeError, ValueError):
            return ()
        if isinstance(value, (list, tuple)) and all(isinstance(item, str) for item in value):
            return tuple(value)
    return ()


def module_exports(module_name: str) -> tuple[str, ...]:
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError:
        # Optional adaptors should still appear in the inventory generated by
        # a core-only environment. Their package __all__ is intentionally a
        # literal so it can be read without importing the optional runtime.
        return _literal_all(module_name)
    return tuple(getattr(module, "__all__", ()))


def collect_inventory() -> dict[str, Any]:
    import _hgraph
    import hgraph

    operators: list[dict[str, Any]] = []
    for name in sorted(_hgraph.operator_names()):
        if name.startswith("__"):
            continue
        shape = _hgraph.operator_parameter_shape(name)
        parameters: list[dict[str, Any]] = []
        variadic = False
        if shape is not None:
            raw_parameters, variadic = shape
            for parameter_name, is_time_series, type_variable, fixed_type in raw_parameters:
                parameters.append({
                    "name": parameter_name,
                    "kind": "time-series" if is_time_series else "scalar",
                    "type_variable": bool(type_variable),
                    "fixed_type": None if fixed_type is None else repr(fixed_type),
                })
        operators.append({
            "name": name,
            "parameters": parameters,
            "variadic": bool(variadic),
        })

    modules = {
        module_name: tuple(sorted(dict.fromkeys(module_exports(module_name))))
        for module_name in PUBLIC_MODULES
    }
    return {
        "root": tuple(sorted(dict.fromkeys(hgraph.__all__))),
        "operators": tuple(operators),
        "modules": modules,
    }


def _display_signature(operator: dict[str, Any]) -> str:
    parameters = [parameter["name"] or "value" for parameter in operator["parameters"]]
    if operator["variadic"]:
        if parameters and parameters[-1] == "args":
            parameters[-1] = "*args"
        else:
            parameters.append("*args")
    if not parameters:
        parameters = ["..."]
    return f"{operator['name']}({', '.join(parameters)})"


def _hlist(names: tuple[str, ...], indent: str = "") -> list[str]:
    if not names:
        return [f"{indent}No separately exported names."]
    lines = [f"{indent}.. hlist::", f"{indent}   :columns: 3", ""]
    lines.extend(f"{indent}   * - ``{name}``" for name in names)
    return lines


def render_rst(inventory: dict[str, Any]) -> str:
    operators = inventory["operators"]
    modules = inventory["modules"]
    lines = [
        "Python API inventory",
        "====================",
        "",
        ".. This file is generated by tools/api_inventory.py. Do not edit it by hand.",
        "",
        "This inventory is generated from the installed ``hgraph`` package and",
        "native operator registry. It complements the curated reference pages:",
        "``hgraph.__all__`` describes wildcard imports, while the operator registry",
        "also supplies lazy module attributes such as ``add_`` and ``filter_``.",
        "Names beginning with two underscores are runtime implementation entries and",
        "are omitted.",
        "",
        ".. list-table:: Inventory summary",
        "   :header-rows: 1",
        "   :widths: 55 15",
        "",
        "   * - Surface",
        "     - Names",
        f"   * - ``hgraph.__all__``",
        f"     - {len(inventory['root'])}",
        "   * - Public lazy operators",
        f"     - {len(operators)}",
        "   * - Public submodules",
        f"     - {len(modules)}",
        "",
        "Top-level wildcard exports",
        "--------------------------",
        "",
    ]
    lines.extend(_hlist(inventory["root"]))
    lines.extend([
        "",
        "Lazy operator registry",
        "----------------------",
        "",
        "The call shapes below are the common parameter prefix reported by the",
        "native overload registry. Concrete accepted types, optional parameters and",
        "return types depend on the overload selected while wiring.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 25 55 20",
        "",
        "   * - Name",
        "     - Registry call shape",
        "     - Parameters",
    ])
    for operator in operators:
        parameter_kinds = ", ".join(
            f"{parameter['name'] or 'value'}: {parameter['kind']}"
            for parameter in operator["parameters"]
        ) or "overload-specific"
        lines.extend([
            f"   * - ``{operator['name']}``",
            f"     - ``{_display_signature(operator)}``",
            f"     - {parameter_kinds}",
        ])

    lines.extend(["", "Public submodules", "-----------------", ""])
    for module_name, exports in modules.items():
        lines.extend([module_name, "~" * len(module_name), ""])
        lines.extend(_hlist(exports))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _typing_parameter_name(name: str, used: set[str]) -> str | None:
    if not name:
        return None
    candidate = f"{name}_" if keyword.iskeyword(name) else name
    if not candidate.isidentifier() or candidate in used:
        return None
    used.add(candidate)
    return candidate


def _shape_key(operator: dict[str, Any]) -> tuple[tuple[str, ...], bool]:
    used: set[str] = set()
    names: list[str] = []
    for parameter in operator["parameters"]:
        name = _typing_parameter_name(parameter["name"], used)
        if name is None:
            return (), True
        names.append(name)
    return tuple(names), operator["variadic"]


def render_operator_stub(inventory: dict[str, Any]) -> str:
    operators = inventory["operators"]
    shapes = sorted({_shape_key(operator) for operator in operators})
    shape_names = {shape: f"_OperatorShape{index:03d}" for index, shape in enumerate(shapes)}
    lines = [
        '"""Generated typing declarations for operators exposed lazily by ``hgraph``.',
        "",
        "Regenerate with ``tools/api_inventory.py``; runtime dispatch remains owned",
        'by the native operator registry."""',
        "",
        "from typing import Any, Protocol, Self",
        "",
        "from ._wiring import WiringPort",
        "",
    ]
    for shape in shapes:
        names, variadic = shape
        class_name = shape_names[shape]
        parameters = [f"{name}: Any = ..." for name in names]
        if variadic:
            if parameters and names[-1] == "args":
                parameters[-1] = "*args: Any"
            else:
                parameters.append("*args: Any")
        if not parameters:
            parameters.append("*args: Any")
        parameters.append("**kwargs: Any")
        lines.extend([
            f"class {class_name}(Protocol):",
            f"    def __call__(self, {', '.join(parameters)}) -> WiringPort | None: ...",
            "    def __getitem__(self, item: Any, /) -> Self: ...",
            "",
        ])
    for operator in operators:
        lines.append(f"{operator['name']}: {shape_names[_shape_key(operator)]}")
    lines.extend(["", "__all__ = ("])
    lines.extend(f'    "{operator["name"]}",' for operator in operators)
    lines.extend([")", ""])
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rst", type=Path, default=DEFAULT_RST)
    parser.add_argument("--stub", type=Path, default=DEFAULT_STUB)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    inventory = collect_inventory()
    outputs = {
        arguments.rst: render_rst(inventory),
        arguments.stub: render_operator_stub(inventory),
    }
    stale = [path for path, content in outputs.items() if not _write_or_check(path, content, arguments.check)]
    if stale:
        for path in stale:
            print(f"stale generated API file: {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
