"""Generate include/hgraph/types/value/unicode_printable.h.

The table lists the code point ranges Python's ``str.isprintable`` rejects,
so ``str_`` can escape a string inside a container exactly as Python's
``repr`` does (runtime spec OP-9). Printability depends on the Unicode
database of the interpreter that runs this script, so the header records
that version; regenerate it with the interpreter the parity reference runs.

    python tools/generate_unicode_printable.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "include"
    / "hgraph"
    / "types"
    / "value"
    / "unicode_printable.h"
)


def non_printable_ranges() -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start = None
    for code_point in range(0x110000):
        printable = chr(code_point).isprintable()
        if not printable and start is None:
            start = code_point
        elif printable and start is not None:
            ranges.append((start, code_point - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges


def render(ranges: list[tuple[int, int]]) -> str:
    rows = "\n".join(
        f"        {{0x{low:06X}, 0x{high:06X}}}," for low, high in ranges
    )
    return f"""#ifndef HGRAPH_TYPES_VALUE_UNICODE_PRINTABLE_H
#define HGRAPH_TYPES_VALUE_UNICODE_PRINTABLE_H

// Generated by tools/generate_unicode_printable.py from Python
// {sys.version.split()[0]} (Unicode {unicodedata.unidata_version}). Do not edit.

#include <algorithm>
#include <array>
#include <cstdint>
#include <string_view>

namespace hgraph::unicode_detail
{{
    inline constexpr std::string_view printable_unicode_version = "{unicodedata.unidata_version}";

    /** Inclusive code point ranges Python's ``str.isprintable`` rejects. */
    inline constexpr std::array<std::array<std::uint32_t, 2>, {len(ranges)}> non_printable_ranges{{{{
{rows}
    }}}};

    /** Python's ``str.isprintable`` for one code point. */
    [[nodiscard]] constexpr bool is_printable(std::uint32_t code_point) noexcept
    {{
        const auto after = std::upper_bound(
            non_printable_ranges.begin(), non_printable_ranges.end(), code_point,
            [](std::uint32_t value, const std::array<std::uint32_t, 2> &range) {{ return value < range[0]; }});
        return after == non_printable_ranges.begin() || code_point > (after - 1)->at(1);
    }}
}}  // namespace hgraph::unicode_detail

#endif  // HGRAPH_TYPES_VALUE_UNICODE_PRINTABLE_H
"""


def main() -> int:
    OUTPUT.write_text(render(non_printable_ranges()))
    print(f"wrote {OUTPUT} (Unicode {unicodedata.unidata_version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
