# Native SDK consumers use the same pinned fetch recipes as the producer.
include("${CMAKE_CURRENT_LIST_DIR}/HgraphFetchDependencies.cmake")
if(NOT TARGET fmt::fmt)
    find_package(fmt ${HGRAPH_FMT_FETCH_VERSION} EXACT CONFIG QUIET)
    if(NOT fmt_FOUND)
        hgraph_fetch_fmt()
    endif()
endif()
if(NOT TARGET spdlog::spdlog)
    # A system spdlog is compatible only with its system fmt.
    if(fmt_FOUND)
        find_package(spdlog ${HGRAPH_SPDLOG_FETCH_VERSION} EXACT CONFIG QUIET)
    endif()
    if(NOT spdlog_FOUND)
        hgraph_fetch_spdlog()
    endif()
endif()
if(NOT TARGET simdjson::simdjson)
    find_package(simdjson ${HGRAPH_SIMDJSON_FETCH_VERSION} EXACT CONFIG QUIET)
    if(NOT simdjson_FOUND)
        hgraph_fetch_simdjson()
        target_compile_features(simdjson PRIVATE cxx_std_20)
    endif()
endif()
if((NOT TARGET Arrow::arrow_shared AND NOT TARGET Arrow::arrow_static) OR
   (NOT TARGET ArrowCompute::arrow_compute_shared AND NOT TARGET ArrowCompute::arrow_compute_static) OR
   (NOT TARGET ArrowAcero::arrow_acero_shared AND NOT TARGET ArrowAcero::arrow_acero_static))
    include("${CMAKE_CURRENT_LIST_DIR}/HgraphArrow.cmake")
endif()
